# Copyright Â© 2026, Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230. Licensed under the Apache License, Version 2.0.
#
# Author: John Grimes

apiVersion: v2
name: fhirpath-lab-api
description: A FHIRPath Lab server backed by the Pathling FHIRPath engine
icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
type: application
version: 1.0.0
maintainers:
  - name: John Grimes
    email: John.Grimes@csiro.au
sources:
  - https://github.com/aehrc/pathling
keywords:
  - fhir
  - fhirpath
  - pathling
