# Copyright Â© 2026, Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230. Licensed under the Apache License, Version 2.0.
#
# Author: John Grimes

fhirpathLabApi:
  image: "ghcr.io/aehrc/fhirpath-lab-api:latest"
  imagePullPolicy: "Always"
  replicas: 1

  service:
    type: "ClusterIP"
    port: 8080

  resources:
    {}
    # requests:
    #   memory: "4Gi"
    #   cpu: "1"
    # limits:
    #   memory: "4Gi"

  config:
    CORS_ALLOWED_ORIGINS: "https://fhirpath-lab.azurewebsites.net,http://localhost:3000"

  tolerations: []
  affinity: {}
  nodeSelector: {}
