apiVersion: v1
entries:
  pathling:
  - annotations:
      artifacthub.io/signKey: |
        fingerprint: F814751C64B5F5E708A8C73FC3C6291FED48678D
        url: https://pathling.csiro.au/helm/pubkey.asc
    apiVersion: v2
    created: "2026-01-21T07:18:29.85656875Z"
    description: A Helm chart for Pathling Server
    digest: c6de3e9eee7a48bc208f8ef57834ec0d161e325450d82d20f0ab94b5c145f22c
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v2
    created: "2026-01-21T07:18:29.856092695Z"
    description: A Helm chart for Pathling Server
    digest: bc3ab10a1915a12c7f7723946681d71c71df707b6388e2b63ed3548b86af1308
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.2.tgz
    version: 1.0.2
  pathling-cache:
  - annotations:
      artifacthub.io/signKey: |
        fingerprint: F814751C64B5F5E708A8C73FC3C6291FED48678D
        url: https://pathling.csiro.au/helm/pubkey.asc
    apiVersion: v2
    appVersion: 1.0.0
    created: "2026-01-21T07:08:07.647343788Z"
    description: A Varnish-based frontend cache optimised for use with Pathling
    digest: 6465c1f95952b486d08fe6fbd6d3cd04867da418f03e832edfc8ec2d75839fc5
    name: pathling-cache
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-cache-1.0.0.tgz
    version: 1.0.0
generated: "2026-01-21T07:18:29.855492327Z"
