apiVersion: v1
entries:
  pathling:
    - annotations:
        artifacthub.io/signKey: |
          fingerprint: F814751C64B5F5E708A8C73FC3C6291FED48678D
          url: https://pathling.csiro.au/helm/pubkey.asc
      apiVersion: v2
      created: "2026-01-21T10:09:57.559142413Z"
      description: A Helm chart for Pathling Server
      digest: 0c0df1f183f682ac1baca07e6581fb90046b018a0e0eed77f2df01d0ffe16e78
      icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
      keywords:
        - spark
        - analytics
        - standards
        - fhir
        - terminology
      maintainers:
        - email: John.Grimes@csiro.au
          name: John Grimes
      name: pathling
      sources:
        - https://github.com/aehrc/pathling
      type: application
      urls:
        - https://pathling.csiro.au/helm/pathling-2.0.0.tgz
      version: 2.0.0
    - apiVersion: v2
      created: "2026-01-21T10:09:57.558697963Z"
      description: A Helm chart for Pathling Server
      digest: bc3ab10a1915a12c7f7723946681d71c71df707b6388e2b63ed3548b86af1308
      icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
      keywords:
        - spark
        - analytics
        - standards
        - fhir
        - terminology
      maintainers:
        - email: John.Grimes@csiro.au
          name: John Grimes
      name: pathling
      sources:
        - https://github.com/aehrc/pathling
      type: application
      urls:
        - https://pathling.csiro.au/helm/pathling-1.0.2.tgz
      version: 1.0.2
  pathling-cache:
    - annotations:
        artifacthub.io/signKey: |
          fingerprint: F814751C64B5F5E708A8C73FC3C6291FED48678D
          url: https://pathling.csiro.au/helm/pubkey.asc
      apiVersion: v2
      created: "2026-01-21T10:09:57.559402558Z"
      description: A Varnish-based frontend cache optimised for use with Pathling Server
      digest: afaaad10ebaed9c35d49cad92a64eee38a5d19216c8895c9098e26d2515463d3
      icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
      keywords:
        - spark
        - analytics
        - standards
        - fhir
        - terminology
      maintainers:
        - email: John.Grimes@csiro.au
          name: John Grimes
      name: pathling-cache
      sources:
        - https://github.com/aehrc/pathling
      type: application
      urls:
        - https://pathling.csiro.au/helm/pathling-cache-1.0.0.tgz
      version: 1.0.0
generated: "2026-01-21T10:09:57.558174567Z"
