# This workflow builds and tests the server module.

name: Test server

# This workflow runs on pull requests that modify server-related files.
on:
  pull_request:
    paths:
      - "server/**"
      - ".github/workflows/test-server.yml"

env:
  # The add-exports and add-opens flags are required for Java 21.
  MAVEN_OPTS: --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED

permissions:
  contents: read
  packages: write

jobs:
  test-server:
    name: Build and test server
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "zulu"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |-
            ${{ runner.os }}-maven-

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run security scan
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: repo
          severity: "MEDIUM,HIGH,CRITICAL"
          scan-ref: .
          format: sarif
          output: trivy-results.sarif
          skip-files: examples/**/*,**/target/**/*
          cache: false

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, test, and push Docker image
        working-directory: server
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn --batch-mode deploy -Pdocker -Dmaven.deploy.skip \
          -Djib.to.tags=\${project.version}-develop \
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=aehrc_pathling -Dsonar.organization=aehrc \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.sarifReportPaths=../trivy-results.sarif
        timeout-minutes: 30

      - name: Save test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: server-surefire-reports
          path: "server/**/surefire-reports/"

      - name: Save coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: |
            server/**/jacoco.exec
            server/**/jacoco.xml
            server/**/target/site/jacoco
          name: server-coverage-reports

      - name: Save built JAR
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: server-jar
          path: server/target/server-*.jar
